import type { Alumni } from "@/types/directory"

export const alumniData: Alumni[] = [
    {
        id: "1",
        name: "Ahmad Fauzi",
        position: "Senior Software Engineer",
        company: "TechCorp Solutions",
        location: "Jakarta, Indonesia",
        gradYear: "2015",
        industry: "Technology",
        city: "Jakarta",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AhmadFauzi",
        bio: "Experienced software engineer with a passion for building scalable applications. Currently leading a team of 8 engineers at TechCorp Solutions. Active mentor in the alumni network.",
    },
    {
        id: "2",
        name: "Siti Aminah",
        position: "Marketing Manager",
        company: "Creative Agency Hub",
        location: "Semarang, Indonesia",
        gradYear: "2018",
        industry: "Marketing",
        city: "Semarang",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SitiAminah",
    },
    {
        id: "3",
        name: "Budi Santoso",
        position: "Civil Engineer",
        company: "BuildIndo Infrastructure",
        location: "Surabaya, Indonesia",
        gradYear: "2012",
        industry: "Engineering",
        city: "Surabaya",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=BudiSantoso",
    },
    {
        id: "4",
        name: "Dewi Lestari",
        position: "Medical Doctor",
        company: "General Hospital Central",
        location: "Jepara, Indonesia",
        gradYear: "2016",
        industry: "Healthcare",
        city: "Jepara",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DewiLestari",
    },
    {
        id: "5",
        name: "Rizky Pratama",
        position: "Project Manager",
        company: "Global Solutions Inc.",
        location: "Jakarta, Indonesia",
        gradYear: "2014",
        industry: "Technology",
        city: "Jakarta",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RizkyPratama",
    },
    {
        id: "6",
        name: "Indah Permata",
        position: "Data Scientist",
        company: "Data Dynamics Co.",
        location: "Bandung, Indonesia",
        gradYear: "2019",
        industry: "Technology",
        city: "Bandung",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=IndahPermata",
    },
    {
        id: "7",
        name: "Hendra Wijaya",
        position: "Senior Architect",
        company: "ArchDesign Studio",
        location: "Singapore",
        gradYear: "2013",
        industry: "Engineering",
        city: "Singapore",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=HendraWijaya",
    },
    {
        id: "8",
        name: "Putri Rahayu",
        position: "Education Specialist",
        company: "Kementerian Pendidikan",
        location: "Jakarta, Indonesia",
        gradYear: "2020",
        industry: "Education",
        city: "Jakarta",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=PutriRahayu",
    },
    {
        id: "9",
        name: "Muhammad Rizki",
        position: "Financial Analyst",
        company: "Bank Mandiri",
        location: "Jakarta, Indonesia",
        gradYear: "2017",
        industry: "Finance",
        city: "Jakarta",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MuhammadRizki",
    },
    {
        id: "10",
        name: "Nurul Hidayah",
        position: "UX Designer",
        company: "Creative Studio",
        location: "Yogyakarta, Indonesia",
        gradYear: "2021",
        industry: "Technology",
        city: "Yogyakarta",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=NurulHidayah",
    },
    {
        id: "11",
        name: "Fajar Setiawan",
        position: "Startup Founder",
        company: "EduTech Indonesia",
        location: "Jakarta, Indonesia",
        gradYear: "2011",
        industry: "Education",
        city: "Jakarta",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=FajarSetiawan",
    },
    {
        id: "12",
        name: "Lina Marlina",
        position: "HR Manager",
        company: "Gojek",
        location: "Jakarta, Indonesia",
        gradYear: "2016",
        industry: "Human Resources",
        city: "Jakarta",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LinaMarlina",
    },
]